language:
    - go

go:
    - 1.2
    - tip

install:
    - go get code.google.com/p/go.tools/cmd/cover
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls

    - go get github.com/coopernurse/gorp
    - go get github.com/mattn/go-sqlite3
    - go get github.com/smartystreets/goconvey/convey

script:
    - ./covergen.sh
    - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
